const reasons: Record<string,string> = {
  ORB_DATA_PROVIDER_UNAVAILABLE:"Alpaca временно не возвращает данные. Повторяем проверку; покупка недоступна.",
  ORB_CLOSED_WAITING_NEW_SIGNAL:"Предыдущая сделка закрыта. Ждём нового роста, возврата и подтверждения.",
  ORB_RETEST_WAIT_BREAKOUT:"Ждём закрытия растущей пятиминутной свечи выше максимума первых 5 минут + $0.01.",
  ORB_RETEST_WAIT_RETURN:"Рост состоялся. Ждём возврата к уровню, не догоняем цену.",
  ORB_RETEST_WAIT_CONFIRMATION:"Цена вернулась к уровню. Ждём подтверждения роста по закрытой пятиминутной свече.",
  ORB_RETEST_WAIT_RECOVERY:"Цена ниже зоны покупки. Ждём восстановления, пока сигнал действует.",
  ORB_RETEST_CONFIRMED:"Возврат и рост подтверждены. Покупка возможна только в указанной зоне после проверки риска.",
  ORB_RETEST_EXPIRED:"Сигнал истёк. Ждём новой последовательности роста и возврата.",
  ORB_RETEST_INVALIDATED:"Условия сигнала нарушены. Ждём нового движения цены.",
  ORB_RETEST_REWARD_INSUFFICIENT:"До цели слишком мало места относительно риска и расчётных издержек. Покупки не будет.",
  ORB_RETEST_DATA_INVALID:"Не удалось подтвердить данные движения цены. Покупка заблокирована.",
  ORB_RETEST_HISTORY_GAP:"В пятиминутных свечах есть пропуск. Ждём полных данных.",
  ORB_RETEST_BARS_STALE:"Нет свежей завершённой пятиминутной свечи. Ждём обновления.",
  ORB_WAITING_PULLBACK:"Ждём снижения до указанной цены или ниже.",
  ORB_PRICE_WITHIN_LIMIT:"Цена не выше установленного предела покупки.",
  ORB_STOP_BREACHED:"Цена достигла защитного стопа или ниже. Покупка запрещена.",
  SPREAD_TOO_WIDE:"Слишком большая разница между ценами покупки и продажи.",
  ORB_SKIPPED_WAITING_RESET:"Пропущено сейчас. Ждём нового движения цены для повторного предложения.",
  ORB_ATTEMPT_CONSUMED:"Этот план уже использован. Новая покупка требует закрытия предыдущей позиции и нового сигнала.",
  ORB_PUBLICATION_UNRESOLVED:"Связь с предложением требует восстановления. Повторный вход заблокирован.",
  ORB_SIP_SUBSCRIPTION_REQUIRED:"Подписка Alpaca не разрешает свежие данные SIP. Подключите доступ к SIP в Plans & Features → Market Data. Доступ проверяется автоматически каждую минуту.",
  ORB_SIP_ACCESS_DENIED:"Alpaca отказала в доступе к SIP (403). Проверьте подписку на данные SIP и используемые API-ключи. Новые входы недоступны.",
  ORB_DATA_CREDENTIALS_REJECTED:"Alpaca отклонила API-ключи (401). Требуется исправить подключение данных.",
  ORB_DATA_RATE_LIMITED:"Alpaca ограничила частоту запросов (429). Повторяем после паузы.",
  ORB_LOADING:"Загружаем данные открытия из Alpaca.",
  ORB_NO_CANDIDATES:"В этой сессии нет кандидатов, прошедших условия ORB. Причины — в статистике отбора.",
  ORB_OPENING_RANGE_FORMING:"Ждём завершения диапазона 09:30–09:35 по Нью-Йорку.",
  ORB_OUTSIDE_ENTRY_SESSION:"Входы доступны после 09:35 ET до установленного времени окончания входов.",
  ORB_UNSUPPORTED_FEED:"Неизвестный источник данных Alpaca. Поддерживаются IEX и SIP.",
  ORB_DATA_ACCESS_DENIED:"Alpaca отклонила доступ к настроенному источнику данных. Проверьте API-ключи.",
  ORB_DATA_FEED_MISMATCH:"Источник текущих данных отличается от источника сохранённого плана. Вход заблокирован.",
  ORB_SESSION_CONFIGURATION_CHANGED:"Источник или версия стратегии изменились после отбора. Сохранённые планы не переписываются; новый отбор — в следующей сессии.",
  ORB_IEX_DOLLAR_VOLUME_LOW:"Средний дневной оборот на IEX меньше $20 млн — порога ликвидности для этой версии.",
  ORB_WAITING_BREAKOUT:"Ждём роста до цены входа. Цены в плане установлены на день.",
  ORB_BREAKOUT_CONFIRMED:"Цена достигла уровня входа. Перед покупкой повторно проверяем цену и риск.",
  ORB_ENTRY_MISSED:"Цена выше предела покупки. Вход сейчас запрещён.",
  ORB_ENTRY_EXPIRED:"Время новых входов по этому плану истекло.",
  ORB_QUOTE_STALE:"Ждём свежую котировку Alpaca.",
  ORB_QUOTE_MISSING:"Нет достоверной котировки.",
  ORB_SERVICE_UNAVAILABLE:"Не удалось проверить данные или счёт. Повторная проверка выполняется автоматически.",
  ORB_HISTORY_INCOMPLETE:"Нет полной истории для 14 предыдущих сессий.",
  ORB_DAILY_VOLUME_LOW:"Средний дневной объём меньше 1 млн акций.",
  ORB_ATR_LOW:"Дневной ATR не превышает $0.50.",
  ORB_PRICE_BELOW_MINIMUM:"Цена открытия не превышает $5.",
  ORB_RELATIVE_VOLUME_LOW:"Объём первых пяти минут меньше среднего объёма того же окна за 14 сессий.",
  ORB_OPENING_NOT_BULLISH:"Первая пятиминутная свеча не растущая; эта версия торгует только покупки.",
  WEEKLY_PNL_UNAVAILABLE:"Недоступен результат периода риска счёта.",
  PORTFOLIO_DRAWDOWN_UNAVAILABLE:"Недоступна просадка счёта.",
};
export const orbReason = (reason: string) => reasons[reason] ?? reason;
export const orbState = (state?:string) => ({EXECUTED:"Исполнено",SKIPPED:"Пропущено",EXPIRED:"Истёк",DISCARDED:"Снят",APPROVING:"Проверяем исполнение",APPROVED:"Одобрено",WAIT:"Ждём цену входа",BUY_ALLOWED:"Проверка входа",BLOCKED:"Вход заблокирован",DATA_BLOCKED:"Нет данных",NO_TRADE:"Нет входа"}[state ?? ""] ?? "План");
export const px = (value: unknown) => value == null || !Number.isFinite(Number(value)) ? "—" : Number(value).toFixed(2);
export const etTime = (value:string) => new Date(value).toLocaleTimeString("ru-RU",{timeZone:"America/New_York",hour:"2-digit",minute:"2-digit"});
