const reasons: Record<string,string> = {
  ORB_SKIPPED_WAITING_RESET:"Пропущено сейчас. Ждём нового движения цены для повторного предложения.",
  ORB_ATTEMPT_CONSUMED:"Решение по этому плану уже принято. Повторного входа сегодня не будет.",
  ORB_PUBLICATION_UNRESOLVED:"Связь с предложением требует восстановления. Повторный вход заблокирован.",
  ORB_SIP_SUBSCRIPTION_REQUIRED:"Подписка Alpaca не разрешает свежие данные SIP. Подключите доступ к SIP в Plans & Features → Market Data. Доступ проверяется автоматически каждую минуту.",
  ORB_SIP_ACCESS_DENIED:"Alpaca отказала в доступе к SIP (403). Проверьте подписку на данные SIP и используемые API-ключи. Новые входы недоступны.",
  ORB_DATA_CREDENTIALS_REJECTED:"Alpaca отклонила API-ключи (401). Требуется исправить подключение данных.",
  ORB_DATA_RATE_LIMITED:"Alpaca ограничила частоту запросов (429). Повторяем после паузы.",
  ORB_LOADING:"Загружаем данные открытия из Alpaca.",
  ORB_NO_CANDIDATES:"В этой сессии нет кандидатов, прошедших условия ORB. Причины — в статистике отбора.",
  ORB_OPENING_RANGE_FORMING:"Ждём завершения диапазона 09:30–09:35 по Нью-Йорку.",
  ORB_OUTSIDE_ENTRY_SESSION:"Входы доступны после 09:35 ET до установленного времени окончания входов.",
  ORB_UNSUPPORTED_FEED:"Неизвестный источник данных Alpaca. Поддерживаются IEX и SIP.",
  ORB_DATA_ACCESS_DENIED:"Alpaca отклонила доступ к настроенному источнику данных. Проверьте API-ключи.",
  ORB_DATA_FEED_MISMATCH:"Источник текущих данных отличается от источника сохранённого плана. Вход заблокирован.",
  ORB_SESSION_CONFIGURATION_CHANGED:"Источник или версия стратегии изменились после отбора. Сохранённые планы не переписываются; новый отбор — в следующей сессии.",
  ORB_IEX_DOLLAR_VOLUME_LOW:"Средний дневной оборот на IEX меньше $20 млн — порога ликвидности для этой версии.",
  ORB_WAITING_BREAKOUT:"Ждём роста до цены входа. Цены в плане установлены на день.",
  ORB_BREAKOUT_CONFIRMED:"Цена достигла уровня входа. Перед покупкой повторно проверяем цену и риск.",
  ORB_ENTRY_MISSED:"Цена выше предела покупки. Вход сейчас запрещён.",
  ORB_ENTRY_EXPIRED:"Время новых входов по этому плану истекло.",
  ORB_QUOTE_STALE:"Ждём свежую котировку Alpaca.",
  ORB_QUOTE_MISSING:"Нет достоверной котировки.",
  ORB_SERVICE_UNAVAILABLE:"Не удалось проверить данные или счёт. Повторная проверка выполняется автоматически.",
  ORB_HISTORY_INCOMPLETE:"Нет полной истории для 14 предыдущих сессий.",
  ORB_DAILY_VOLUME_LOW:"Средний дневной объём меньше 1 млн акций.",
  ORB_ATR_LOW:"Дневной ATR не превышает $0.50.",
  ORB_PRICE_BELOW_MINIMUM:"Цена открытия не превышает $5.",
  ORB_RELATIVE_VOLUME_LOW:"Объём первых пяти минут меньше среднего объёма того же окна за 14 сессий.",
  ORB_OPENING_NOT_BULLISH:"Первая пятиминутная свеча не растущая; эта версия торгует только покупки.",
  WEEKLY_PNL_UNAVAILABLE:"Недоступен результат периода риска счёта.",
  PORTFOLIO_DRAWDOWN_UNAVAILABLE:"Недоступна просадка счёта.",
};
export const orbReason = (reason: string) => reasons[reason] ?? reason;
export const orbState = (state?:string) => ({EXECUTED:"Исполнено",SKIPPED:"Пропущено",EXPIRED:"Истёк",DISCARDED:"Снят",APPROVING:"Проверяем исполнение",APPROVED:"Одобрено",WAIT:"Ждём цену входа",BUY_ALLOWED:"Проверка входа",BLOCKED:"Вход заблокирован",DATA_BLOCKED:"Нет данных",NO_TRADE:"Нет входа"}[state ?? ""] ?? "План");
export const px = (value: unknown) => value == null || !Number.isFinite(Number(value)) ? "—" : Number(value).toFixed(2);
export const etTime = (value:string) => new Date(value).toLocaleTimeString("ru-RU",{timeZone:"America/New_York",hour:"2-digit",minute:"2-digit"});
